version: '3.8'
services:
  psql:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - psql:/var/lib/postgresql/data
      - ./src/cores/database/data/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./src/cores/database/data/dml.sql:/docker-entrypoint-initdb.d/dml.sql

volumes:
  psql:
    driver: local